baseURL = "http://thabbott.github.io/"
languageCode = "en-us"
title = "Tristan Abbott"
theme = "xmin"

[[menu.main]]
    name = "Tristan Abbott"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 2
[[menu.main]]
    name = "Media"
    url = "/media/"
    weight = 3
[[menu.main]]
    name = "CV"
    url = "/doc/thabbott.pdf"
    weight = 4

[params]
    footer = "&copy; Tristan Abbott 2022"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
