baseURL = "http://thabbott.github.io/"
languageCode = "en-us"
title = "Tristan Abbott"
theme = "xmin"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 3

[params]
    footer = "&copy; Tristan Abbott 2020 | [Accessibility](https://accessibility.mit.edu)"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
